site_name: pytest-llmeval
site_description: A pytest plugin to evaluate/benchmark LLM prompts
site_author: Kevin Schaul

theme: readthedocs

repo_url: https://github.com/kevinschaul/pytest-llmeval

pages:
- Home: index.md
